import britMila1 from "../assets/Photos/SIDUR-530.png";
import britMila2 from "../assets/Photos/SIDUR-531.png";
import britMila3 from "../assets/Photos/SIDUR-532.png";
import britMila4 from "../assets/Photos/SIDUR-533.png";
import britMila5 from "../assets/Photos/SIDUR-534.png";
import britMila6 from "../assets/Photos/SIDUR-535.png";
import britMila7 from "../assets/Photos/SIDUR-536.png";
import britMila8 from "../assets/Photos/SIDUR-537.png";
import britMila9 from "../assets/Photos/SIDUR-538.png";
