import kabalatShabat1 from "../assets/Photos/SIDUR-233.png";
import kabalatShabat2 from "../assets/Photos/SIDUR-234.png";
import kabalatShabat3 from "../assets/Photos/SIDUR-235.png";
import kabalatShabat4 from "../assets/Photos/SIDUR-236.png";
import kabalatShabat5 from "../assets/Photos/SIDUR-237.png";
import kabalatShabat6 from "../assets/Photos/SIDUR-238.png";
import kabalatShabat7 from "../assets/Photos/SIDUR-239.png";
import kabalatShabat8 from "../assets/Photos/SIDUR-240.png";
import kabalatShabat9 from "../assets/Photos/SIDUR-241.png";
