import seferJanuca1 from "../assets/Photos/SIDUR-484.png";
import seferJanuca2 from "../assets/Photos/SIDUR-485.png";
import seferJanuca3 from "../assets/Photos/SIDUR-486.png";
import seferJanuca4 from "../assets/Photos/SIDUR-487.png";
import seferJanuca5 from "../assets/Photos/SIDUR-488.png";
import seferJanuca6 from "../assets/Photos/SIDUR-489.png";
import seferJanuca7 from "../assets/Photos/SIDUR-490.png";
import seferJanuca8 from "../assets/Photos/SIDUR-491.png";
import seferJanuca9 from "../assets/Photos/SIDUR-492.png";
